hardness = 0.2
layer_type = 1
physics_type = 1
resource_id = "glass_clear"

[light_transmission_color]
pack_id = "@self"
resource_key = "glass/glass_clear"
resource_type = "color"

[break_sfx]
pack_id = "@self"
resource_key = "sfx/glass_break"
resource_type = "audio"

[name]
pack_id = "@self"
resource_key = "glass_clear"
resource_type = "string"

[place_sfx]
pack_id = "@self"
resource_key = "sfx/glass_place"
resource_type = "audio"

[texture]
pack_id = "@self"
resource_key = "tiles/glass_clear"
resource_type = "texture"
