#金锭
resource_id = "ingot_gold"
recipe_group = 2
min_technology_level = 1
exact_match = false

[[input]]
required_tag = "nugget_gold"
required_weight = 3

[[input]]
required_tag = "fuel"
required_weight = 1

[output]
amount = 1
[output.item]
pack_id = "@self"
resource_key = "ingot_gold"
resource_type = 20
