#铜粒
resource_id = "nugget_copper"
recipe_group = 2
min_technology_level = 1
exact_match = false

[[input]]
required_tag = "raw_copper"
required_weight = 1

[[input]]
required_tag = "fuel"
required_weight = 1

[output]
amount = 1
[output.item]
pack_id = "@self"
resource_key = "nugget_copper"
resource_type = 20
