resource_id = "pickaxe_stone"
recipe_group = 1
min_technology_level = 1

[[input]]
required_tag = "stone"
required_weight = 3

[[input]]
required_tag = "wooden_stick"
required_weight = 2

[output]
amount = 1

[output.item]
pack_id = "@self"
resource_key = "pickaxe_stone"
resource_type = 3

[[output.ability_item_ref]]
amount = 1
locked = true

[output.ability_item_ref.item]
pack_id = "@self"
resource_key = "stone_mining"
resource_type = 4
