resource_id = "oak_leaf"
rolls = 1
empty_weight = 80

[[pool]]
weight = 15
min = 1
max = 1

[pool.item]
pack_id = "@self"
resource_key = "oak_leaf"
resource_type = 2

[[pool]]
weight = 5
min = 1
max = 1

[pool.item]
pack_id = "@self"
resource_key = "oak_sapling"
resource_type = 2
