resource_id = "oak_leaf"
rolls = 1

[[pool]]
weight = 70
min = 1
max = 1

[pool.item]
pack_id = "@self"
resource_key = "oak_leaf"
resource_type = 2

[[pool]]
weight = 5
min = 1
max = 2

[pool.item]
pack_id = "@self"
resource_key = "wooden_stick"
resource_type = 20

[[pool]]
weight = 25
min = 1
max = 1

[pool.item]
pack_id = "@self"
resource_key = "oak_sapling"
resource_type = 2
