resource_id = "cave"
surface_proximity = 0.49
strictness_surface_proximity = 0.1

[bgm]
pack_id = "@self"
resource_key = "bgm/biome_cave"
resource_type = 12

[parallax_background]
pack_id = "@self"
resource_key = "backgrounds/default"
resource_type = 7

[[decors]]
pack_id = "@self"
resource_key = "cave_fill"
resource_type = 14

[[decors]]
pack_id = "@self"
resource_key = "cave_ore_copper_mineral"
resource_type = 14

[[decors]]
pack_id = "@self"
resource_key = "cave_ore_iron_mineral"
resource_type = 14

[[decors]]
pack_id = "@self"
resource_key = "cave_ore_gold_mineral"
resource_type = 14


[[decors]]
pack_id = "@self"
resource_key = "cave_wall_fill"
resource_type = 14
