[[string]]
resourceId = "dataPacksName"
value = "GlimmerWorks"

[[string]]
resourceId = "dataPacksDescription"
value = "The official core data pack for GlimmerWorks, providing essential game definitions and content."

[[string]]
resourceId = "dirt"
value = "dirt"

[[string]]
resourceId = "grass"
value = "grass"

[[string]]
resourceId = "sand"
value = "sand"


[[string]]
resourceId = "snow"
value = "snow"


[[string]]
resourceId = "wooden_pickaxe"
value = "wooden pickaxe"


[[string]]
resourceId = "simple_dig"
value = "Simple dig module"



[[string]]
resourceId = "standard_dig"
value = "Standard dig module"


[[string]]
resourceId = "oak_wood"
value = "oak wood"


[[string]]
resourceId = "oak_leaf"
value = "oak leaf"


[[string]]
resourceId = "oak"
value = "oak"


[[string]]
resourceId = "area_marker"
value = "Precision surveying instrument"

[[string]]
resourceId = "mining_gain_1"
value = "Mining Bonus I"


[[string]]
resourceId = "mining_gain_2"
value = "Mining Bonus II"


[[string]]
resourceId = "mining_gain_3"
value = "Mining Bonus III"

[[string]]
resourceId = "mining_gain_4"
value = "Mining Bonus IV"

[[string]]
resourceId = "mining_gain_5"
value = "Mining Bonus V"

[[string]]
resourceId = "precision_mining"
value = "Precision Mining"

[[string]]
resourceId = "fumble_chance_1"
value = "Fumble I"

[[string]]
resourceId = "fumble_chance_2"
value = "Fumble II"

[[string]]
resourceId = "fumble_chance_3"
value = "Fumble III"

[[string]]
resourceId = "chain_mining_1"
value = "Chain Mining I"

[[string]]
resourceId = "chain_mining_2"
value = "Chain Mining II"

[[string]]
resourceId = "chain_mining_3"
value = "Chain Mining III"
