[[string]]
resource_id = "dataPacksName"
value = "グリマーワークス"

[[string]]
resource_id = "dataPacksDescription"
value = "グリマーワークス公式コアデータパックです。ゲームの基本定義とコンテンツを提供します。"

[[string]]
resource_id = "dirt"
value = "土"

[[string]]
resource_id = "grass"
value = "草土"

[[string]]
resource_id = "sand"
value = "砂"

[[string]]
resource_id = "snow"
value = "雪"

[[string]]
resource_id = "wooden_pickaxe"
value = "木のつるはし"

[[string]]
resource_id = "simple_dig"
value = "簡易採掘モジュール"

[[string]]
resource_id = "standard_dig"
value = "標準採掘モジュール"

[[string]]
resource_id = "oak_wood"
value = "オークの木板"

[[string]]
resource_id = "oak_leaf"
value = "オークの葉"

[[string]]
resource_id = "oak"
value = "オーク"

[[string]]
resource_id = "area_marker"
value = "せいみつそくていき"

[[string]]
resource_id = "mining_gain_1"
value = "採掘ブーストⅠ"

[[string]]
resource_id = "mining_gain_2"
value = "採掘ブーストⅡ"

[[string]]
resource_id = "mining_gain_3"
value = "採掘ブーストⅢ"

[[string]]
resource_id = "mining_gain_4"
value = "採掘ブーストⅣ"

[[string]]
resource_id = "mining_gain_5"
value = "採掘ブーストⅤ"

[[string]]
resource_id = "precision_mining"
value = "せいみつさいくつ"

[[string]]
resource_id = "fumble_chance_1"
value = "滑り手 I"

[[string]]
resource_id = "fumble_chance_2"
value = "滑り手 II"

[[string]]
resource_id = "fumble_chance_3"
value = "滑り手 III"

[[string]]
resource_id = "chain_mining_1"
value = "チェーン収集 I"

[[string]]
resource_id = "chain_mining_2"
value = "チェーン収集 II"

[[string]]
resource_id = "chain_mining_3"
value = "チェーン収集 III"

[[string]]
resource_id = "stone"
value = "石"

[[string]]
resource_id = "ore_copper"
value = "銅鉱石"

[[string]]
resource_id = "ore_iron"
value = "鉄鉱石"

[[string]]
resource_id = "ore_gold"
value = "金鉱石"

[[string]]
resource_id = "berry_cream"
value = "イチゴクリームブロック"

[[string]]
resource_id = "strawberry_puree"
value = "イチゴピューレ"

[[string]]
resource_id = "ore_candy"
value = "キャンディ鉱石"

[[string]]
resource_id = "ore_blue_candy"
value = "ブルーキャンディ鉱石"

[[string]]
resource_id = "torch"
value = "松明"

[[string]]
resource_id = "dirt_wall"
value = "土の壁"

[[string]]
resource_id = "candy_block"
value = "キャンディブロック"

[[string]]
resource_id = "candy_wrapper_wall"
value = "飴紙の壁"

[[string]]
resource_id = "stone_wall"
value = "石の壁"

