[[string]]
resourceId = "dataPacksName"
value = "微光工坊"

[[string]]
resourceId = "dataPacksDescription"
value = "微光工坊官方核心数据包，提供游戏的基础定义和内容。"

[[string]]
resourceId = "dirt"
value = "泥土"


[[string]]
resourceId = "grass"
value = "草地"


[[string]]
resourceId = "sand"
value = "沙子"


[[string]]
resourceId = "snow"
value = "雪"


[[string]]
resourceId = "wooden_pickaxe"
value = "木镐"


[[string]]
resourceId = "simple_dig"
value = "简易挖掘模块"


[[string]]
resourceId = "standard_dig"
value = "标准挖掘模块"

[[string]]
resourceId = "oak_wood"
value = "橡木木板"


[[string]]
resourceId = "oak_leaf"
value = "橡木树叶"


[[string]]
resourceId = "oak"
value = "橡木"

[[string]]
resourceId = "area_marker"
value = "精准测绘仪"

[[string]]
resourceId = "mining_gain_1"
value = "挖掘增益I"


[[string]]
resourceId = "mining_gain_2"
value = "挖掘增益II"


[[string]]
resourceId = "mining_gain_3"
value = "挖掘增益III"

[[string]]
resourceId = "mining_gain_4"
value = "挖掘增益IV"

[[string]]
resourceId = "mining_gain_5"
value = "挖掘增益V"

[[string]]
resourceId = "precision_mining"
value = "精准采集"

[[string]]
resourceId = "fumble_chance_1"
value = "手滑I"

[[string]]
resourceId = "fumble_chance_2"
value = "手滑II"

[[string]]
resourceId = "fumble_chance_3"
value = "手滑III"

[[string]]
resourceId = "chain_mining_1"
value = "连锁采集I"

[[string]]
resourceId = "chain_mining_2"
value = "连锁采集II"

[[string]]
resourceId = "chain_mining_3"
value = "连锁采集III"
