[[string]]
resourceId = "dataPacksName"
value = "微光工坊"

[[string]]
resourceId = "dataPacksDescription"
value = "微光工坊官方核心資料包，提供遊戲的基礎定義和內容。"

[[string]]
resourceId = "dirt"
value = "泥土"


[[string]]
resourceId = "grass"
value = "草地"


[[string]]
resourceId = "sand"
value = "沙子"


[[string]]
resourceId = "snow"
value = "雪"


[[string]]
resourceId = "wooden_pickaxe"
value = "木鎬"

[[string]]
resourceId = "simple_dig"
value = "簡易挖掘模組"


[[string]]
resourceId = "standard_dig"
value = "標準挖掘模組"

[[string]]
resourceId = "oak_wood"
value = "橡木木闆"

[[string]]
resourceId = "oak_leaf"
value = "橡木樹葉"


[[string]]
resourceId = "oak"
value = "橡木"


[[string]]
resourceId = "area_marker"
value = "精準測繪儀"

[[string]]
resourceId = "mining_gain_1"
value = "採掘增益I"

[[string]]
resourceId = "mining_gain_2"
value = "採掘增益II"

[[string]]
resourceId = "mining_gain_3"
value = "採掘增益III"

[[string]]
resourceId = "mining_gain_4"
value = "採掘增益IV"

[[string]]
resourceId = "mining_gain_5"
value = "採掘增益V"

[[string]]
resourceId = "precision_mining"
value = "精準采集"

[[string]]
resourceId = "fumble_chance_1"
value = "手滑I"

[[string]]
resourceId = "fumble_chance_2"
value = "手滑II"

[[string]]
resourceId = "fumble_chance_3"
value = "手滑III"

[[string]]
resourceId = "chain_mining_1"
value = "連鎖採集I"

[[string]]
resourceId = "chain_mining_2"
value = "連鎖採集II"

[[string]]
resourceId = "chain_mining_3"
value = "連鎖採集III"
