resource_id = "oak"
leaf_data_index = 0
trunk_data_index = 1
trunk_height_max = 9
trunk_height_min = 3
has_leaves = true
leaf_radius = 3
leaf_cluster_count = 1
leaf_vertical_spacing = 1
trunk_width = 1
trunk_tile_layer = 2
leaf_tile_layer = 2

[[condition]]
processor_id = "surface"

[[condition]]
processor_id = "biome"

[condition.config]
[[condition.config.definition]]
key = "biome_0"
type = "ref"

[condition.config.definition.value]
pack_id = "@self"
resource_key = "plains"
resource_type = 8

[[condition]]
processor_id = "height"

[condition.config]
[[condition.config.definition]]
key = "maxHeightPercent"
type = "float"
value = 0.8

[[condition.config.definition]]
key = "minHeightPercent"
type = "float"
value = 0.2

[[condition]]
processor_id = "hSpacing"

[condition.config]
[[condition.config.definition]]
key = "minDistance"
type = "int"
value = 8

[[data]]
pack_id = "@self"
resource_key = "oak_leaf"
resource_type = 2

[[data]]
pack_id = "@self"
resource_key = "oak"
resource_type = 2
