generator_id = 'static'
resource_id = 'start_room'

[[tile_info]]
x = 0
y = 0

[tile_info.tile]
pack_id = '@self'
resource_key = 'oak_wood'
resource_type = 'tile'

[[tile_info]]
x = 1
y = 0

[tile_info.tile]
pack_id = '@self'
resource_key = 'oak_wood'
resource_type = 'tile'

[[tile_info]]
x = 2
y = 0

[tile_info.tile]
pack_id = '@self'
resource_key = 'oak_wood'
resource_type = 'tile'

[[tile_info]]
x = 3
y = 0

[tile_info.tile]
pack_id = '@self'
resource_key = 'oak_wood'
resource_type = 'tile'

[[tile_info]]
x = 4
y = 0

[tile_info.tile]
pack_id = '@self'
resource_key = 'oak_wood'
resource_type = 'tile'

[[tile_info]]
x = 5
y = 0

[tile_info.tile]
pack_id = '@self'
resource_key = 'oak_wood'
resource_type = 'tile'

[[tile_info]]
x = 6
y = 0

[tile_info.tile]
pack_id = '@self'
resource_key = 'oak_wood'
resource_type = 'tile'

[[tile_info]]
x = 7
y = 0

[tile_info.tile]
pack_id = '@self'
resource_key = 'oak_wood'
resource_type = 'tile'

[[tile_info]]
x = 8
y = 0

[tile_info.tile]
pack_id = '@self'
resource_key = 'oak_wood'
resource_type = 'tile'

[[tile_info]]
x = 9
y = 0

[tile_info.tile]
pack_id = '@self'
resource_key = 'oak_wood'
resource_type = 'tile'

[[tile_info]]
x = 10
y = 0

[tile_info.tile]
pack_id = '@self'
resource_key = 'oak_wood'
resource_type = 'tile'

[[tile_info]]
x = 11
y = 0

[tile_info.tile]
pack_id = '@self'
resource_key = 'oak_wood'
resource_type = 'tile'

[[tile_info]]
x = 0
y = 1

[tile_info.tile]
pack_id = '@self'
resource_key = 'oak_wood'
resource_type = 'tile'

[[tile_info]]
x = 1
y = 1

[tile_info.tile]
pack_id = '@core'
resource_key = 'air'
resource_type = 'tile'

[[tile_info]]
x = 2
y = 1

[tile_info.tile]
pack_id = '@core'
resource_key = 'air'
resource_type = 'tile'

[[tile_info]]
x = 3
y = 1

[tile_info.tile]
pack_id = '@core'
resource_key = 'air'
resource_type = 'tile'

[[tile_info]]
x = 4
y = 1

[tile_info.tile]
pack_id = '@core'
resource_key = 'air'
resource_type = 'tile'

[[tile_info]]
x = 5
y = 1

[tile_info.tile]
pack_id = '@core'
resource_key = 'air'
resource_type = 'tile'

[[tile_info]]
x = 6
y = 1

[tile_info.tile]
pack_id = '@core'
resource_key = 'air'
resource_type = 'tile'

[[tile_info]]
x = 7
y = 1

[tile_info.tile]
pack_id = '@core'
resource_key = 'air'
resource_type = 'tile'

[[tile_info]]
x = 8
y = 1

[tile_info.tile]
pack_id = '@core'
resource_key = 'air'
resource_type = 'tile'

[[tile_info]]
x = 9
y = 1

[tile_info.tile]
pack_id = '@core'
resource_key = 'air'
resource_type = 'tile'

[[tile_info]]
x = 10
y = 1

[tile_info.tile]
pack_id = '@core'
resource_key = 'air'
resource_type = 'tile'

[[tile_info]]
x = 11
y = 1

[tile_info.tile]
pack_id = '@self'
resource_key = 'oak_wood'
resource_type = 'tile'

[[tile_info]]
x = 0
y = 2

[tile_info.tile]
pack_id = '@core'
resource_key = 'air'
resource_type = 'tile'

[[tile_info]]
x = 1
y = 2

[tile_info.tile]
pack_id = '@core'
resource_key = 'air'
resource_type = 'tile'

[[tile_info]]
x = 2
y = 2

[tile_info.tile]
pack_id = '@core'
resource_key = 'air'
resource_type = 'tile'

[[tile_info]]
x = 3
y = 2

[tile_info.tile]
pack_id = '@core'
resource_key = 'air'
resource_type = 'tile'

[[tile_info]]
x = 4
y = 2

[tile_info.tile]
pack_id = '@core'
resource_key = 'air'
resource_type = 'tile'

[[tile_info]]
x = 5
y = 2

[tile_info.tile]
pack_id = '@core'
resource_key = 'air'
resource_type = 'tile'

[[tile_info]]
x = 6
y = 2

[tile_info.tile]
pack_id = '@core'
resource_key = 'air'
resource_type = 'tile'

[[tile_info]]
x = 7
y = 2

[tile_info.tile]
pack_id = '@core'
resource_key = 'air'
resource_type = 'tile'

[[tile_info]]
x = 8
y = 2

[tile_info.tile]
pack_id = '@core'
resource_key = 'air'
resource_type = 'tile'

[[tile_info]]
x = 9
y = 2

[tile_info.tile]
pack_id = '@core'
resource_key = 'air'
resource_type = 'tile'

[[tile_info]]
x = 10
y = 2

[tile_info.tile]
pack_id = '@core'
resource_key = 'air'
resource_type = 'tile'

[[tile_info]]
x = 11
y = 2

[tile_info.tile]
pack_id = '@core'
resource_key = 'air'
resource_type = 'tile'

[[tile_info]]
x = 0
y = 3

[tile_info.tile]
pack_id = '@core'
resource_key = 'air'
resource_type = 'tile'

[[tile_info]]
x = 1
y = 3

[tile_info.tile]
pack_id = '@core'
resource_key = 'air'
resource_type = 'tile'

[[tile_info]]
x = 2
y = 3

[tile_info.tile]
pack_id = '@core'
resource_key = 'air'
resource_type = 'tile'

[[tile_info]]
x = 3
y = 3

[tile_info.tile]
pack_id = '@core'
resource_key = 'air'
resource_type = 'tile'

[[tile_info]]
x = 4
y = 3

[tile_info.tile]
pack_id = '@core'
resource_key = 'air'
resource_type = 'tile'

[[tile_info]]
x = 5
y = 3

[tile_info.tile]
pack_id = '@core'
resource_key = 'air'
resource_type = 'tile'

[[tile_info]]
x = 6
y = 3

[tile_info.tile]
pack_id = '@core'
resource_key = 'air'
resource_type = 'tile'

[[tile_info]]
x = 7
y = 3

[tile_info.tile]
pack_id = '@core'
resource_key = 'air'
resource_type = 'tile'

[[tile_info]]
x = 8
y = 3

[tile_info.tile]
pack_id = '@core'
resource_key = 'air'
resource_type = 'tile'

[[tile_info]]
x = 9
y = 3

[tile_info.tile]
pack_id = '@core'
resource_key = 'air'
resource_type = 'tile'

[[tile_info]]
x = 10
y = 3

[tile_info.tile]
pack_id = '@core'
resource_key = 'air'
resource_type = 'tile'

[[tile_info]]
x = 11
y = 3

[tile_info.tile]
pack_id = '@core'
resource_key = 'air'
resource_type = 'tile'

[[tile_info]]
x = 0
y = 4

[tile_info.tile]
pack_id = '@self'
resource_key = 'oak_leaf'
resource_type = 'tile'

[[tile_info]]
x = 1
y = 4

[tile_info.tile]
pack_id = '@self'
resource_key = 'oak_leaf'
resource_type = 'tile'

[[tile_info]]
x = 2
y = 4

[tile_info.tile]
pack_id = '@self'
resource_key = 'oak_leaf'
resource_type = 'tile'

[[tile_info]]
x = 3
y = 4

[tile_info.tile]
pack_id = '@self'
resource_key = 'oak_leaf'
resource_type = 'tile'

[[tile_info]]
x = 4
y = 4

[tile_info.tile]
pack_id = '@self'
resource_key = 'oak_leaf'
resource_type = 'tile'

[[tile_info]]
x = 5
y = 4

[tile_info.tile]
pack_id = '@self'
resource_key = 'oak_leaf'
resource_type = 'tile'

[[tile_info]]
x = 6
y = 4

[tile_info.tile]
pack_id = '@self'
resource_key = 'oak_leaf'
resource_type = 'tile'

[[tile_info]]
x = 7
y = 4

[tile_info.tile]
pack_id = '@self'
resource_key = 'oak_leaf'
resource_type = 'tile'

[[tile_info]]
x = 8
y = 4

[tile_info.tile]
pack_id = '@self'
resource_key = 'oak_leaf'
resource_type = 'tile'

[[tile_info]]
x = 9
y = 4

[tile_info.tile]
pack_id = '@self'
resource_key = 'oak_leaf'
resource_type = 'tile'

[[tile_info]]
x = 10
y = 4

[tile_info.tile]
pack_id = '@self'
resource_key = 'oak_leaf'
resource_type = 'tile'

[[tile_info]]
x = 11
y = 4

[tile_info.tile]
pack_id = '@self'
resource_key = 'oak_leaf'
resource_type = 'tile'
