resource_id = "pickaxe_wooden"

[[add_items]]
amount = 1

[[add_items.ability_item_ref]]
amount = 1

[add_items.ability_item_ref.item]
pack_id = "@self"
resource_key = "simple_dig"
resource_type = 4

[add_items.item]
pack_id = "@self"
resource_key = "pickaxe_wooden"
resource_type = 3
