resource_id = "wooden_pickaxe"

[[add_items]]
amount = 1

[[add_items.ability_item_ref]]
amount = 1

[add_items.ability_item_ref.item]
pack_id = "@self"
resource_key = "simple_dig"
resource_type = "ability"

[add_items.item]
pack_id = "@self"
resource_key = "wooden_pickaxe"
resource_type = "composable"
