resourceId = "wooden_pickaxe"
[[addItems]]
amount = 1
[addItems.item]
packId = "@self"
resourceType = "composable"
resourceKey = "wooden_pickaxe"
[[addItems.abilityItemRef]]
amount = 1
[addItems.abilityItemRef.item]
packId = "@self"
resourceType = "ability"
resourceKey = "standard_dig"
