resourceId = "chain_mining_3"
canUseAlone = true
ability = "none"

[texture]
packId = "@self"
resourceType = "texture"
resourceKey = "items/data_module"

[name]
packId = "@self"
resourceType = "string"
resourceKey = "chain_mining_3"

[abilityConfig]
chainMiningRadius = 9
