ability = "none"
can_use_alone = true
resource_id = "chain_mining_1"

[ability_config]
chain_mining_radius = 3

[name]
pack_id = "@self"
resource_key = "chain_mining_1"
resource_type = "string"

[texture]
pack_id = "@self"
resource_key = "items/data_module"
resource_type = "texture"
