resourceId = "fumble_chance_2"
canUseAlone = false
ability = "none"

[texture]
packId = "@self"
resourceType = "texture"
resourceKey = "items/data_module"

[name]
packId = "@self"
resourceType = "string"
resourceKey = "fumble_chance_2"

[abilityConfig]
fumbleProbability = 0.1
