resourceId = "fumble_chance_3"
canUseAlone = false
ability = "none"

[texture]
packId = "@self"
resourceType = "texture"
resourceKey = "items/data_module.png"

[name]
packId = "@self"
resourceType = "string"
resourceKey = "fumble_chance_3"

[abilityConfig]
fumbleProbability = 0.15
