ability = 1
can_use_alone = false
resource_id = "hand_mining"
unbreakable = true

[ability_config]
allow_mine_block = true
mining_efficiency = 0.45

[name]
pack_id = "@self"
resource_key = "hand"
resource_type = 1

[texture]
pack_id = "@self"
resource_key = "items/function_module"
resource_type = 7
