resourceId = "mining_gain_4"
canUseAlone = false
ability = "none"

[texture]
packId = "@self"
resourceType = "texture"
resourceKey = "items/data_module"

[name]
packId = "@self"
resourceType = "string"
resourceKey = "mining_gain_4"

[abilityConfig]
miningEfficiency = 2.4
