resourceId = "mining_gain_1"
canUseAlone = false
ability = "none"

[texture]
packId = "@self"
resourceType = "texture"
resourceKey = "items/data_module"

[name]
packId = "@self"
resourceType = "string"
resourceKey = "mining_gain_1"

[abilityConfig]
miningEfficiency = 0.6
