resourceId = "mining_gain_2"
canUseAlone = false
ability = "none"

[texture]
packId = "@self"
resourceType = "texture"
resourceKey = "items/data_module"

[name]
packId = "@self"
resourceType = "string"
resourceKey = "mining_gain_2"

[abilityConfig]
miningEfficiency = 1.2
