resourceId = "precision_mining"
canUseAlone = false
ability = "none"

[texture]
packId = "@self"
resourceType = "texture"
resourceKey = "items/data_module"

[name]
packId = "@self"
resourceType = "string"
resourceKey = "precision_mining"

[abilityConfig]
enablePrecisionMining = true
