resourceId = "simple_dig"
canUseAlone = false
ability = "dig"

[texture]
packId = "@self"
resourceType = "texture"
resourceKey = "items/function_module.png"

[name]
packId = "@self"
resourceType = "string"
resourceKey = "simple_dig"

[abilityConfig]
allowMineBlock = true
miningEfficiency = 0.7
