ability = "dig"
can_use_alone = false
resource_id = "standard_dig"

[ability_config]
allow_mine_block = true
mining_efficiency = 1.0

[name]
pack_id = "@self"
resource_key = "standard_dig"
resource_type = "string"

[texture]
pack_id = "@self"
resource_key = "items/function_module"
resource_type = "texture"
