resource_id = "plateau"
surface_proximity = 0.8
strictness_surface_proximity = 1.0

[parallax_background]
pack_id = "@self"
resource_key = "backgrounds/default"
resource_type = 7

[bgm]
pack_id = "@self"
resource_key = "bgm/biome_plateau"
resource_type = 12

[[decors]]
pack_id = "@self"
resource_key = "plateau_fill"
resource_type = 14

[[decors]]
pack_id = "@self"
resource_key = "plains_wall_fill"
resource_type = 14
