elevation = 0.75
erosion = 1.0
humidity = 0.4
resource_id = "plateau"
temperature = 0.3
weirdness = 0.0
strictness_elevation = 5.0
temperature_elevation = 2.0

[bgm]
pack_id = "@self"
resource_key = "bgm/biome_plateau"
resource_type = "audio"

[[decors]]
pack_id = "@self"
resource_key = "plateau_fill"
resource_type = "decor"

[[decors]]
pack_id = "@self"
resource_key = "plains_wall_fill"
resource_type = "decor"