resource_id = "candy_land_ore_blue_candy_mineral"
layer_type = 1
noise_type = 0
frequency = 0.1
ore_spawn_min_noise_threshold = 0.99
ore_spawn_max_noise_threshold =  0.99
seed_offset = 2048
min_spawn_elevation = 0.0
max_spawn_elevation = 1.0
[ore]
pack_id = "@self"
resource_type  = "tile"
resource_key = "ore_blue_candy"
