resource_id = "candy_land"
weirdness = 0.95
strictness_weirdness = 1.5
surface_proximity = 0.5
strictness_surface_proximity = 1.3

[bgm]
pack_id = "@self"
resource_key = "bgm/biome_candy_land"
resource_type = 12

[parallax_background]
pack_id = "@self"
resource_key = "backgrounds/default"
resource_type = 7

[[decors]]
pack_id = "@self"
resource_key = "candy_land_fill"
resource_type = 14

[[decors]]
pack_id = "@self"
resource_key = "candy_land_ore_candy_mineral"
resource_type = 14

[[decors]]
pack_id = "@self"
resource_key = "candy_land_ore_blue_candy_mineral"
resource_type = 14

[[decors]]
pack_id = "@self"
resource_key = "candy_land_surface"
resource_type = 14

[[decors]]
pack_id = "@self"
resource_key = "candy_land_wall_fill"
resource_type = 14
