elevation = 0.5
erosion = 1.0
humidity = 0.5
resource_id = "plains"
temperature = 0.5
weirdness = 0.0

[bgm]
pack_id = "@self"
resource_key = "bgm/biome_plains"
resource_type = "audio"

[[decors]]
pack_id = "@self"
resource_key = "plains_fill"
resource_type = "decor"

[[decors]]
pack_id = "@self"
resource_key = "plains_surface"
resource_type = "decor"
