ability = 1
can_use_alone = false
resource_id = "{mat}_mining"
max_durability = {dur}

[ability_config]
allow_mine_block = true
mining_efficiency = {eff}

[name]
pack_id = "@self"
resource_key = "{mat}_mining"
resource_type = 1

[texture]
pack_id = "@self"
resource_key = "items/function_module"
resource_type = 7
