resource_id = "{id}"
slot_size = {slot}
max_durability = {dur}

[name]
pack_id = "@self"
resource_key = "{id}"
resource_type = 1

[texture]
pack_id = "@self"
resource_key = "items/{id}"
resource_type = 7
