resource_id = "{tool}_{mat}"
recipe_group = 1
min_technology_level = 1

[[input]]
required_tag = "{head_tag}"
required_weight = {head_weight}

[[input]]
required_tag = "wooden_stick"
required_weight = 2

[output]
amount = 1

[output.item]
pack_id = "@self"
resource_key = "{tool}_{mat}"
resource_type = 3

[[output.ability_item_ref]]
amount = 1
locked = true

[output.ability_item_ref.item]
pack_id = "@self"
resource_key = "{mat}_mining"
resource_type = 4

[[output.ability_item_ref]]
amount = 1
locked = true

[output.ability_item_ref.item]
pack_id = "@self"
resource_key = "{layer_key}"
resource_type = 4
