hardness = 0.1
layer_type = 1
physics_type = 0
resource_id = "light_4"
emission_radius = 4

[emission_color]
pack_id = "@self"
resource_key = "light_color"
resource_type = "color"

[break_sfx]
pack_id = "@self"
resource_key = "sfx/wood_break"
resource_type = "audio"

[name]
pack_id = "@self"
resource_key = "light_block"
resource_type = "string"

[place_sfx]
pack_id = "@self"
resource_key = "sfx/wood_place"
resource_type = "audio"

[texture]
pack_id = "@self"
resource_key = "lights/light_4"
resource_type = "texture"
