resource_id = "coal"

[[tags]]
name = "coal"

[[tags]]
name = "fuel"
value = 8

[name]
pack_id = "@self"
resource_key = "coal"
resource_type = 1

[texture]
pack_id = "@self"
resource_key = "materials/coal"
resource_type = 7
