resource_id = "ingot_iron"
tags = ["ingot_iron"]
[name]
pack_id = "@self"
resource_key = "ingot_iron"
resource_type = 1

[texture]
pack_id = "@self"
resource_key = "items/ingot_iron"
resource_type = 7
