resource_id = "nugget_copper"
tags = ["nugget_copper"]
[name]
pack_id = "@self"
resource_key = "nugget_copper"
resource_type = 1

[texture]
pack_id = "@self"
resource_key = "items/nugget_copper"
resource_type = 7
