resource_id = "nugget_gold"
tags = ["nugget_gold"]
[name]
pack_id = "@self"
resource_key = "nugget_gold"
resource_type = 1

[texture]
pack_id = "@self"
resource_key = "items/nugget_gold"
resource_type = 7
