resource_id = "raw_gold"

[[tags]]
name = "raw_gold"

[name]
pack_id = "@self"
resource_key = "raw_gold"
resource_type = 1

[texture]
pack_id = "@self"
resource_key = "materials/raw_gold"
resource_type = 7
