resource_id = "raw_iron"

[[tags]]
name = "raw_iron"

[name]
pack_id = "@self"
resource_key = "raw_iron"
resource_type = 1

[texture]
pack_id = "@self"
resource_key = "items/raw_iron"
resource_type = 7
