hardness = 0.5
layer_type = 0
physics_type = 1
resource_id = "berry_cream"

[break_sfx]
pack_id = "@self"
resource_key = "sfx/dirt_break"
resource_type = "audio"

[name]
pack_id = "@self"
resource_key = "berry_cream"
resource_type = "string"

[place_sfx]
pack_id = "@self"
resource_key = "sfx/dirt_place"
resource_type = "audio"

[texture]
pack_id = "@self"
resource_key = "tiles/berry_cream"
resource_type = "texture"
