hardness = 0.6
layer_type = 2
physics_type = 0
resource_id = "candy_wrapper_wall"

[break_sfx]
pack_id = "@self"
resource_key = "sfx/dirt_break"
resource_type = "audio"

[name]
pack_id = "@self"
resource_key = "candy_wrapper_wall"
resource_type = "string"

[place_sfx]
pack_id = "@self"
resource_key = "sfx/dirt_place"
resource_type = "audio"

[texture]
pack_id = "@self"
resource_key = "tiles/candy_wrapper_wall"
resource_type = "texture"
