resourceId = "oak"
physicsType = 1
hardness = 1.5
layerType = 0
customLootTable = true
allowChainMining = true

[texture]
packId = "@self"
resourceType = "texture"
resourceKey = "tiles/oak"

[name]
packId = "@self"
resourceType = "string"
resourceKey = "oak"

[lootTable]
packId = "@self"
resourceType = "loot"
resourceKey = "oak"

[breakSFX]
packId = "@self"
resourceType = "audio"
resourceKey = "sfx/block_break"

[blockPlaceSFX]
packId = "@self"
resourceType = "audio"
resourceKey = "sfx/block_place"

