allow_chain_mining = true
custom_loot_table = true
hardness = 1.5
layer_type = 0
physics_type = 1
resource_id = "oak"

[break_sfx]
pack_id = "@self"
resource_key = "sfx/wood_break"
resource_type = "audio"

[loot_table]
pack_id = "@self"
resource_key = "oak"
resource_type = "loot"

[name]
pack_id = "@self"
resource_key = "oak"
resource_type = "string"

[place_sfx]
pack_id = "@self"
resource_key = "sfx/wood_place"
resource_type = "audio"

[texture]
pack_id = "@self"
resource_key = "tiles/oak"
resource_type = "texture"
