allow_chain_mining = true
custom_loot_table = true
hardness = 1.5
layer_type = 0
physics_type = 1
resource_id = 'oak'

[place_sfx]
pack_id = '@self'
resource_key = 'sfx/block_place'
resource_type = 'audio'

[break_sfx]
pack_id = '@self'
resource_key = 'sfx/block_break'
resource_type = 'audio'

[loot_table]
pack_id = '@self'
resource_key = 'oak'
resource_type = 'loot'

[name]
pack_id = '@self'
resource_key = 'oak'
resource_type = 'string'

[texture]
pack_id = '@self'
resource_key = 'tiles/oak'
resource_type = 'texture'
