resourceId = "oak_leaf"
physicsType = 1
hardness = 0.2
layerType = 0
allowChainMining = true

[texture]
packId = "@self"
resourceType = "texture"
resourceKey = "tiles/oak_leaf"

[name]
packId = "@self"
resourceType = "string"
resourceKey = "oak_leaf"

[breakSFX]
packId = "@self"
resourceType = "audio"
resourceKey = "sfx/block_break"

[blockPlaceSFX]
packId = "@self"
resourceType = "audio"
resourceKey = "sfx/block_place"
