hardness = 0.9
layer_type = 0
physics_type = 1
resource_id = "oak_wood"

[break_sfx]
pack_id = "@self"
resource_key = "sfx/wood_break"
resource_type = "audio"

[name]
pack_id = "@self"
resource_key = "oak_wood"
resource_type = "string"

[place_sfx]
pack_id = "@self"
resource_key = "sfx/wood_place"
resource_type = "audio"

[texture]
pack_id = "@self"
resource_key = "tiles/oak_wood"
resource_type = "texture"
