hardness = 0.9
layer_type = 1
physics_type = 1
resource_id = "ore_candy"

[light_source]
pack_id = "@core"
resource_key = "none"
resource_type = "light_source"

[light_mask]
pack_id = "@core"
resource_key = "fill"
resource_type = "light_mask"

[break_sfx]
pack_id = "@self"
resource_key = "sfx/wood_break"
resource_type = "audio"

[name]
pack_id = "@self"
resource_key = "ore_candy"
resource_type = "string"

[place_sfx]
pack_id = "@self"
resource_key = "sfx/wood_place"
resource_type = "audio"

[texture]
pack_id = "@self"
resource_key = "tiles/ore_candy"
resource_type = "texture"
