hardness = 1.0
layer_type = 2
physics_type = 1
resource_id = "stone_2x2"
tile_width = 2
tile_height = 2

[light_source]
pack_id = "@core"
resource_key = "none"
resource_type = 16

[back_light_mask]
pack_id = "@core"
resource_key = "low"
resource_type = 17

[side_light_mask]
pack_id = "@core"
resource_key = "medium"
resource_type = 17

[break_sfx]
pack_id = "@self"
resource_key = "sfx/stone_break"
resource_type = 12

[name]
pack_id = "@self"
resource_key = "stone"
resource_type = 1

[place_sfx]
pack_id = "@self"
resource_key = "sfx/stone_place"
resource_type = 12

[texture]
pack_id = "@self"
resource_key = "tiles/stone"
resource_type = 7


