hardness = 1.0
layer_type = 2
physics_type = 1
resource_id = "stone"

[light_source]
pack_id = "@core"
resource_key = "none"
resource_type = "light_source"

[light_mask]
pack_id = "@core"
resource_key = "fill"
resource_type = "light_mask"

[break_sfx]
pack_id = "@self"
resource_key = "sfx/stone_break"
resource_type = "audio"

[name]
pack_id = "@self"
resource_key = "stone"
resource_type = "string"

[place_sfx]
pack_id = "@self"
resource_key = "sfx/stone_place"
resource_type = "audio"

[texture]
pack_id = "@self"
resource_key = "tiles/stone"
resource_type = "texture"

[light_transmission_color]
pack_id = "@self"
resource_key = "shading_color"
resource_type = "color"

