hardness = 0.3
layer_type = 0
physics_type = 1
resource_id = "strawberry_puree"

[break_sfx]
pack_id = "@self"
resource_key = "sfx/dirt_break"
resource_type = "audio"

[name]
pack_id = "@self"
resource_key = "strawberry_puree"
resource_type = "string"

[place_sfx]
pack_id = "@self"
resource_key = "sfx/dirt_place"
resource_type = "audio"

[texture]
pack_id = "@self"
resource_key = "tiles/strawberry_puree"
resource_type = "texture"
