hardness = 0.5
layer_type = 2
physics_type = 0
resource_id = "torch"

[light_source]
pack_id = "@core"
resource_key = "none"
resource_type = "light_source"

[light_mask]
pack_id = "@core"
resource_key = "fill"
resource_type = "light_mask"

[break_sfx]
pack_id = "@self"
resource_key = "sfx/wood_break"
resource_type = "audio"

[name]
pack_id = "@self"
resource_key = "torch"
resource_type = "string"

[place_sfx]
pack_id = "@self"
resource_key = "sfx/wood_place"
resource_type = "audio"

[texture]
pack_id = "@self"
resource_key = "tiles/ore_gold"
resource_type = "texture"
