hardness = 0.5
layer_type = 2
physics_type = 0
resource_id = "torch"

[light_source]
pack_id = "@core"
resource_key = "none"
resource_type = 16

[back_light_mask]
pack_id = "@core"
resource_key = "low"
resource_type = 17

[side_light_mask]
pack_id = "@core"
resource_key = "medium"
resource_type = 17

[break_sfx]
pack_id = "@self"
resource_key = "sfx/wood_break"
resource_type = 12

[name]
pack_id = "@self"
resource_key = "torch"
resource_type = 1

[place_sfx]
pack_id = "@self"
resource_key = "sfx/wood_place"
resource_type = 12

[texture]
pack_id = "@self"
resource_key = "tiles/ore_gold"
resource_type = 7
