resourceId = "player"
isPlayer = true
movementAcceleration = 6.0
airControlFactor = 1.0
maxSpeed = 18.0
bodyType = 2
allowBodySleep = false
friction = 0.0
fixedRotation = true


[textureOffset]
x = -0.7
y = 1.0

[box2dFilter]
categoryBits = 1
maskBits = 2

[shape]
packId = "@self"
resourceType = "shape"
resourceKey = "player_shape"

[texture]
packId = "@self"
resourceType = "texture"
resourceKey = "player"

[[groundCheckRayCast]]
[groundCheckRayCast.origin]
x = 0.0
y = 0.0

[groundCheckRayCast.translation]
x = 0.0
y = -1.5

[groundCheckRayCast.filter]
categoryBits = 1
maskBits = 2

[[groundCheckRayCast]]
[groundCheckRayCast.origin]
x = -0.6
y = 0.0

[groundCheckRayCast.translation]
x = -0.0
y = -1.5

[groundCheckRayCast.filter]
categoryBits = 1
maskBits = 2

[[groundCheckRayCast]]
[groundCheckRayCast.origin]
x = 0.6
y = 0.0

[groundCheckRayCast.translation]
x = -0.0
y = -1.5

[groundCheckRayCast.filter]
categoryBits = 1
maskBits = 2
