air_control_factor = 1.0
allow_body_sleep = false
body_type = 2
fixed_rotation = true
friction = 0.0
is_player = true
max_speed = 18.0
movement_acceleration = 6.0
resource_id = 'player'

[box2d_filter]
category_bits = 1
mask_bits = 2

[[ground_check_ray_cast]]
[ground_check_ray_cast.filter]
category_bits = 1
mask_bits = 2

[ground_check_ray_cast.origin]
x = 0.0
y = 0.0

[ground_check_ray_cast.translation]
x = 0.0
y = -1.5

[[ground_check_ray_cast]]
[ground_check_ray_cast.filter]
category_bits = 1
mask_bits = 2

[ground_check_ray_cast.origin]
x = -0.6
y = 0.0

[ground_check_ray_cast.translation]
x = -0.0
y = -1.5

[[ground_check_ray_cast]]
[ground_check_ray_cast.filter]
category_bits = 1
mask_bits = 2

[ground_check_ray_cast.origin]
x = 0.6
y = 0.0

[ground_check_ray_cast.translation]
x = -0.0
y = -1.5

[shape]
pack_id = '@self'
resource_key = 'player_shape'
resource_type = 'shape'

[texture]
pack_id = '@self'
resource_key = 'player'
resource_type = 'texture'

[texture_offset]
x = -0.7
y = 1.0
